### PR TITLE
Fix for handling of protocol updates by the catch-up downloader.

### LINKED ISSUE #568: Catch-up downloader mishandles protocol updates
**Bug Description**
The catch-up downloader does not handle protocol updates correctly. After encountering a protocol update, the downloader will skip chunks of blocks for the new protocol version based on the assessed chain height at the start of the import. The simplest fix for this is not to skip chunks after any chunk has been imported.

**Steps to Reproduce**
Run a node from genesis with flags: `--download-blocks-from https://catchup.mainnet.concordium.software/blocks.idx --no-bootstrap t` (for mainnet).

**Expected Result**
The node catches up past protocol updates.

**Actual Result**
The node does not catch up past the first protocol update.

Relevant log:
```
2022-10-26T08:37:49.967260400Z: INFO: Skov: Received block e3f4124d9eab622e1ace187dfbd70b34909b503b87001501d35c390393d67184 (7)
2022-10-26T08:37:49.968705800Z: INFO: Skov: Receive statistics: blocksReceivedCount=1 blockLastReceived=1.6667734699652174e9 blockReceiveLatencyEMA=3265424.4465217404 blockReceiveLatencyEMSD=9796273.339565221 blockReceivePeriodEMA=Nothing blockReceivePeriodEMSD=Nothing
2022-10-26T08:37:49.970178900Z: TRACE: Skov: Verifying block with election difficulty 2.5e-2
2022-10-26T08:37:49.980590500Z: INFO: Skov: Block e3f4124d9eab622e1ace187dfbd70b34909b503b87001501d35c390393d67184 (7) arrived
2022-10-26T08:37:49.980633700Z: INFO: Skov: Arrive statistics: blocksVerifiedCount=1 blockLastArrive=1.6667734699802246e9 blockArriveLatencyEMA=3265424.44802247 blockArriveLatencyEMSD=9796273.34406741 blockArrivePeriodEMA=Nothing blockArrivePeriodEMSD=Nothing 
transactionsPerBlockEMA=0.0 transactionsPerBlockEMSD=0.0
2022-10-26T08:37:49.980858400Z: TRACE: Runner: Released global state lock on thread ThreadId 151
2022-10-26T08:37:49.981085900Z: TRACE: Runner: Acquired global state lock on thread ThreadId 151
2022-10-26T08:37:49.983239000Z: INFO: Skov: Block e3f4124d9eab622e1ace187dfbd70b34909b503b87001501d35c390393d67184 is finalized at height 1077517 with finalization delta=0
2022-10-26T08:37:49.983475100Z: INFO: Skov: Finalization statistics: finalizationCount=1 lastFinalizedTime=1.6667734699832253e9 finalizationPeriodEMA=Nothing finalizationPeriodEMSD=Nothing
2022-10-26T08:37:49.991299200Z: DEBUG: Skov: Blocks e3f4124d9eab622e1ace187dfbd70b34909b503b87001501d35c390393d67184 marked finalized
2022-10-26T08:37:49.991738100Z: INFO: Kontrol: Starting protocol update.
2022-10-26T08:37:49.992021800Z: DEBUG: Skov: Migrating existing global state.
2022-10-26T08:37:50.187584800Z: DEBUG: Skov: Initializing finalization with context = ()
2022-10-26T08:37:50.187619700Z: DEBUG: Skov: Initializing finalization with initial state = finIndex: 1 finHeight: 1 currentRound:PassiveCurrentRound (PassiveFinalizationRound {passiveWitnesses = fromList []})
 pendingMessages:[]
 finQueue: FinalizationQueue {_fqFirstIndex = 1, _fqProofs = fromList []}
2022-10-26T08:37:50.191291300Z: TRACE: Regenesis callback hit
2022-10-26T08:37:50.191319700Z: DEBUG: Skov: Processed finalization in 0.2078692s
2022-10-26T08:37:50.192022500Z: TRACE: Afgjort: Finalization complete. Pending messages: fromList []
2022-10-26T08:37:50.192220600Z: DEBUG: Afgjort: Starting passive finalization round: height=1077518 delta=0
2022-10-26T08:37:50.192457800Z: TRACE: Runner: Released global state lock on thread ThreadId 151
2022-10-26T08:37:50.195393200Z: TRACE: Skipping chunk blocks-1-1.dat: no blocks above last finalized block height
2022-10-26T08:37:50.195401800Z: TRACE: Skipping chunk blocks-1-100001.dat: no blocks above last finalized block height
2022-10-26T08:37:50.195406300Z: TRACE: Skipping chunk blocks-1-200001.dat: no blocks above last finalized block height
2022-10-26T08:37:50.195408600Z: TRACE: Skipping chunk blocks-1-300001.dat: no blocks above last finalized block height
2022-10-26T08:37:50.195411000Z: TRACE: Skipping chunk blocks-1-400001.dat: no blocks above last finalized block height
2022-10-26T08:37:50.195413700Z: TRACE: Skipping chunk blocks-1-500001.dat: no blocks above last finalized block height
2022-10-26T08:37:50.195416000Z: TRACE: Skipping chunk blocks-1-600001.dat: no blocks above last finalized block height
2022-10-26T08:37:50.195418300Z: TRACE: Skipping chunk blocks-1-700001.dat: no blocks above last finalized block height
2022-10-26T08:37:50.195421000Z: TRACE: Skipping chunk blocks-2-1.dat: no blocks above last finalized block height
2022-10-26T08:37:50.195423500Z: TRACE: Skipping chunk blocks-2-100001.dat: no blocks above last finalized block height
2022-10-26T08:37:50.195425800Z: TRACE: Skipping chunk blocks-2-200001.dat: no blocks above last finalized block height
2022-10-26T08:37:50.195428100Z: TRACE: Skipping chunk blocks-2-300001.dat: no blocks above last finalized block height
2022-10-26T08:37:50.195430300Z: TRACE: Skipping chunk blocks-2-400001.dat: no blocks above last finalized block height
2022-10-26T08:37:50.195432700Z: TRACE: Skipping chunk blocks-2-500001.dat: no blocks above last finalized block height
2022-10-26T08:37:50.195435100Z: TRACE: Skipping chunk blocks-2-600001.dat: no blocks above last finalized block height
2022-10-26T08:37:50.195436900Z: TRACE: Skipping chunk blocks-2-700001.dat: no blocks above last finalized block height
2022-10-26T08:37:50.195438500Z: TRACE: Skipping chunk blocks-2-800001.dat: no blocks above last finalized block height
2022-10-26T08:37:50.195440300Z: TRACE: Skipping chunk blocks-2-900001.dat: no blocks above last finalized block height
2022-10-26T08:37:50.195643600Z: INFO: Downloading the catch-up file from https://catchup.mainnet.concordium.software/blocks-2-1000001.dat to C:\Users\Thomas\mainnet\data\.tmpjZFEFj
```

**Versions**
- Software Version 4.5.0/4.4.x

### PR DESCRIPTION
**Pull request by td202**
## Purpose

Fixes #568.

Previously, the catch-up downloader would skip importing chunks where the genesis index was less than the genesis index at start up, or the height of all blocks (from latest genesis) was less than the height at start-up. This meant that after a protocol update the downloader could end up skipping chunks and then trying to process later chunks that have insufficient context.

## Changes

This changes the handling to only skip an initial portion of chunks. Once a valid chunk is encountered, all subsequent chunks will be imported (until a failure occurs).

## Checklist

- [X] My code follows the style of this project.
- [X] The code compiles without warnings.
- [X] I have performed a self-review of the changes.
- [X] I have documented my code, in particular the intent of the
      hard-to-understand areas.

### CODE REVIEW

File: concordium-node/src/bin/cli.rs [hunk 1]
```diff
@@ -608,6 +608,7 @@ async fn import_missing_blocks(
         genesis_hash
     );
 
+    let mut mayskip = true;
```
Comment (abizjak) [inline concordium-node/src/bin/cli.rs:611]:
```suggestion
    // The `last_finalized_block_height` is relative for the starting genesis index.
    // If we are catching up beyond a protocol update we need to start from 0
    // at that genesis index. Instead of observing whether a protocol update has
    // occurred we instead go with the simpler, but equally good solution,
    // of only skipping some chunks at the beginning of the import.
    // This flag indicates whether we have stopped skipping at the beginning of the
    // out of band catchup.
    let mut mayskip = true;
```

Comment (abizjak) [reply concordium-node/src/bin/cli.rs:611]: Formatting is probably off.

**Review by abizjak — APPROVED** [review]

**Review by EmilLa1 — APPROVED** [review]
