### PR TITLE
Prevent the baker thread from starting when it is not needed.

### LINKED ISSUE #952: Confusing logging when starting at P6.
**Bug Description**

The logging when the node starts in P6 is not great

```
2023-07-05T20:38:38.007348457Z: INFO: Runner: Starting baker thread
2023-07-05T20:38:38.007361291Z: INFO: Runner: Baking thread is not required and will shut down.
2023-07-05T20:38:38.007364386Z: INFO: Runner: Exiting baker thread
```

is confusing since it might look like something is off with baking, but that's not the case.

**Steps to Reproduce**

Start node in protocol 6.

**Versions**
- Software Version: 6.0.{0,1}

### PR DESCRIPTION
**Pull request by td202**
## Purpose

Closes #952 

This prevents the baker thread from starting when it is not needed by the consensus version, and thus avoid the attendant logging. A DEBUG-level log message does note that the baker thread is not required.

## Changes

- Suppress starting the baker thread when it is not required for the current consensus version.
- Make the log message for when the baker thread is shut down more reassuring.

## Checklist

- [ ] My code follows the style of this project.
- [ ] The code compiles without warnings.
- [ ] I have performed a self-review of the changes.
- [ ] I have documented my code, in particular the intent of the
      hard-to-understand areas.
- [ ] (If necessary) I have updated the CHANGELOG.

### CODE REVIEW

File: concordium-consensus/src/Concordium/MultiVersion.hs [hunk 1]
```diff
@@ -1242,6 +1242,21 @@ startBaker mvr@MultiVersionRunner{mvBaker = Just Baker{..}, ..} = do
...
+                EVersionedConfigurationV0{} -> True
+                EVersionedConfigurationV1{} -> False
+        if required
+            then a
+            else
+                mvLog
+                    Runner
+                    LLDebug
+                    "The current consensus version does not require a baker thread, so it will not \
+                    \be started"
```
Comment (abizjak) [inline concordium-consensus/src/Concordium/MultiVersion.hs:1259]: I think this log message isn't really useful, and I think it is confusing, to anybody apart from somebody who knows the code and its history. It's a bit hard to appreciate the distinction that a baker **thread** will not be started, but that baking will still happen, just via a different mechanism.

The code is so simple here that I don't think we need to log not doing the action.

File: concordium-consensus/src/Concordium/MultiVersion.hs [hunk 2]
```diff
@@ -1228,7 +1228,7 @@ startBaker MultiVersionRunner{mvBaker = Nothing, ..} =
         Runner
         LLError
         "Attempted to start baker thread, but consensus was started without baker credentials."
-startBaker mvr@MultiVersionRunner{mvBaker = Just Baker{..}, ..} = do
+startBaker mvr@MultiVersionRunner{mvBaker = Just Baker{..}, ..} = whenBakerRequired $ do
```
Comment (limemloh) [inline concordium-consensus/src/Concordium/MultiVersion.hs:1231]: Consider adding to the doc comment above that this function is only interesting for older protocol versions and does nothing for newer versions

File: concordium-consensus/src/Concordium/MultiVersion.hs [hunk 3]
```diff
@@ -1228,7 +1228,7 @@ startBaker MultiVersionRunner{mvBaker = Nothing, ..} =
         Runner
         LLError
         "Attempted to start baker thread, but consensus was started without baker credentials."
```
Comment (limemloh) [inline concordium-consensus/src/Concordium/MultiVersion.hs:1230]: I might be wrong, but won't this still be logged in the new consensus? The message seems only relevant for the old consensus.

Comment (td202) [reply concordium-consensus/src/Concordium/MultiVersion.hs:1230]: This should never happen because the Rust code only `startBaker` when there are baker credentials.

**Review by abizjak — APPROVED** [review]
Looks good.

**Review by limemloh — APPROVED** [review]
