### PR TITLE
Consensus exception handling

### LINKED ISSUE #1233: Exception Handling
When an unrecoverable exception occurs in the consensus, ensure the following:

* The exception is logged at ERROR level.
* Consensus does not continue to execute past that point, since we cannot trust that it will behave correctly.

Note: such unrecoverable exceptions are generally a result of bugs, and as such should not occur. (They could also potentially occur if the node's state is somehow tampered with or corrupted externally.) These can include observing an invariant violation in the state. While it is not good for everything to shut down, it is generally better than the alternative of continuing in some way, which could end up causing wider damage to the chain.

### PR DESCRIPTION
**Pull request by td202**
## Purpose

Closes #1233

This improves the handling of exceptions in consensus so that, if an unrecoverable exception occurs (e.g. an invariant violation), then consensus cannot continue actively.

## Changes

- When an (unrecoverable) exception occurs in a thread holding the global write lock, the lock is put into a poisoned state. When another thread attempts to acquire the lock, it will also raise an exception.
- Ensure that such exceptions are handled appropriately.
- Add a `ResultConsensusFailure` return code to the FFI `receive` functions indicating that an exception has occurred and consensus has been stopped.
- On the Rust side, observing `ConsensusFailure` results in a panic.

## Checklist

- [X] My code follows the style of this project.
- [X] The code compiles without warnings.
- [X] I have performed a self-review of the changes.
- [X] I have documented my code, in particular the intent of the
      hard-to-understand areas.
- [X] (If necessary) I have updated the CHANGELOG.

### CODE REVIEW

File: concordium-consensus/src/Concordium/MultiVersion.hs [hunk 1]
```diff
@@ -500,6 +501,25 @@ data CatchUpStatusBufferState
...
+    deriving (Eq)
+
+-- | An exception indicating that the global state lock was poisoned by an error in another thread.
+--  This indicates that some invariants of the global state may have been violated, and is not
+--  recoverable.
+data GlobalLockPoisonError = GlobalLockPoisonError
+    deriving (Eq, Show, Typeable)
+
+instance Exception GlobalLockPoisonError where
+    displayException _ = "The global state lock was poisoned by an error in another thread."
```
Comment (drsk0) [inline concordium-consensus/src/Concordium/MultiVersion.hs:521]: Maybe worth pointing out, that the error is unrecoverable here as well.

**Review by drsk0 — APPROVED** [review]
Looks good :fire: .

**Review by eb-concordium — APPROVED** [review]
