### PR TITLE
Fix regression in transaction verification logic.

### LINKED ISSUE #318: Incompatibility between node versions < 4 and 4. Node version 4 does not catch up with testnet.
**Bug Description**

This is a regression bug due to an incorrect bound check, using `>` instead of `>=`.

It means that some transactions that are processed by the node version 3 are not processed by node version 4.

This means that a node version 4 is not compatible with existing mainnet and testnet, if they have transactions with stated energy = maxBlockEnergy.

**Versions**
- Software Version: 4.*

### PR DESCRIPTION
**Pull request by abizjak**
## Purpose

Transactions which were previously (in node version 3.*) accepted were now rejected. Specifically
transactions that allow for maxBlockEnergy amount of energy to be used should be
allowed since they were allowed by previous protocol and node versions.

Fixes #318

## Changes

- Correct the check for maximum block energy.
- Add regression test.

## Checklist

- [x] My code follows the style of this project.
- [x] The code compiles without warnings.
- [x] I have performed a self-review of the changes.
- [x] I have documented my code, in particular the intent of the
      hard-to-understand areas.
- [ ] (If necessary) I have updated the CHANGELOG.

### CODE REVIEW

**Review by EmilLa1 — APPROVED** [review]

File: concordium-consensus/tests/consensus/ConcordiumTests/ReceiveTransactionsTest.hs [hunk 1]
```diff
@@ -345,6 +353,8 @@ data TestEnergyParam
   -- ^The tranasction will be provided with a too little amount of energy for
   -- the particular transaction.
   | TooMuch
+  -- ^The tranasction will be provided with exactly maximum block energy amount.
+  | MaxBlockEnergy
   -- ^The energy provided was more than what is allowed in a block,
   -- and as such the transaction will be rejected.
```
Comment (td202) [inline concordium-consensus/tests/consensus/ConcordiumTests/ReceiveTransactionsTest.hs:359]:
```suggestion
  -- ^The energy provided was more than what is allowed in a block,
  -- and as such the transaction will be rejected.
  | MaxBlockEnergy
  -- ^The transaction will be provided with exactly maximum block energy amount.
```

File: concordium-consensus/tests/consensus/ConcordiumTests/ReceiveTransactionsTest.hs [hunk 2]
```diff
@@ -377,6 +387,7 @@ mkAccountTransaction expiry validSignature nonce validSender energyAmount =
     theCost = case energyAmount of
       TooLittle -> 0
       TooMuch -> maxBound
```
Comment (td202) [inline concordium-consensus/tests/consensus/ConcordiumTests/ReceiveTransactionsTest.hs:389]: Perhaps making this `maxBlockEnergy + 1` would be a better test.

**Review by td202 — APPROVED** [review]
