### PR TITLE
Fix dead block access

### LINKED ISSUE #179: Block parent is sometimes deemed missing
**Bug Description**

```
2021-10-03T12:23:07.861279649Z: INFO: Skov: Finalization statistics: finalizationCount=26585 lastFinalizedTime=1.6332637878612645e9 finalizationPeriodEMA=Just 1.4626803686410766e-2 finalizationPeriodEMSD=Just 4.948750310804371e-2
2021-10-03T12:23:07.861645200Z: DEBUG: Skov: Block 5533cb484c6ffa4a09060dad06aeac8a50fa30cb04fd4ae901fba8b30684764b marked finalized
2021-10-03T12:23:07.861660720Z: ERROR: TreeState: Failed to find block d3b55ae6d0fd21e889fa3d6798da704324d355dfa54d64c3e168b7f6a3a1f5ee
2021-10-03T12:23:07.861667390Z: ERROR: TreeState: Block status: Just (BlockAlive d3b55ae6d0fd21e889fa3d6798da704324d355dfa54d64c3e168b7f6a3a1f5ee)
2021-10-03T12:23:07.861672100Z: ERROR: TreeState: Couldn't find parent block in disk
concordium-node: user error (Couldn't find parent block in disk)
concordium-node: warning: too many hs_exit()s
```
(this is on testnet during normal "start node and catch up")

**Steps to Reproduce**

This bug is not reliably reproducible. I have not seen it on my workstation at work, but trying to catch up on this machine (at home) triggers it somewhat consistently (after a few minutes of catchup, depending on what peers I get).

The bug seems to depend on 
1. the vagaries of the Haskell runtime and when it decides to run finalizers for weak pointers. We seem to be using them incorrectly since we have weak pointers to compound types, and documentation explicitly states that
```
WARNING: weak pointers to ordinary non-primitive Haskell types are particularly fragile, because the compiler is free to optimise away or duplicate the underlying data structure. Therefore attempting to place a finalizer on an ordinary Haskell type may well result in the finalizer running earlier than you expected. This is not a problem for caches and memo tables where early finalization is benign.
```
2. the order in which blocks are marked as finalized. If multiple blocks are marked as finalized at the same time then they are marked so from most recent backwards. (See #135 as well). This means that we can be in a situation where a parent of a block that is already marked as finalized is not yet finalized. Combined with (1) and the fact that in https://github.com/Concordium/concordium-node/blob/5204e08188d1c0cf1954f1c3cc551d45bcb3fca5/concordium-consensus/src/Concordium/GlobalState/Persistent/TreeState.hs#L425 we only consider the cases where the weak pointer is not null, or the block is finalized, means we sometimes try to look up a live, but non-finalized block while trying to get the block parent.

**Expected Result**

The node does not crash.

**Actual Result**

The node sometimes crashes during catchup.

**Versions**
- Software Version: 1.1.2 (but all at least 1.1.* verisons are affected).
- OS: Linux (built with dynamic linking)

### PR DESCRIPTION
**Pull request by abizjak**
## Purpose

Fix occasional crashes in high-stress situations.

In combination with #180 closes #179 

Partially addresses #135 by writing finalized blocks by increasing height.

1. For the persistent block storage block parent pointers are weak pointers.
2. During finalization blocks are in some cases marked as dead before their descendants. The node sometimes looks up a block parent that is dead.
3. Depending on the scheduling of the garbage collector the parent block is already reclaimed, or at the very least the weak pointer cannot be dereferenced, leading to a node crash.

## Changes

Instead of marking blocks as dead immediately during finalization we accumulate them and mark them as dead at the end after we no longer need to look up their parents.

This relies on #180.

## Checklist

- [x] My code follows the style of this project.
- [x] The code compiles without warnings.
- [x] I have performed a self-review of the changes.
- [x] I have documented my code, in particular the intent of the
      hard-to-understand areas.
- [x] (If necessary) I have updated the CHANGELOG.

### CODE REVIEW

File: concordium-consensus/src/Concordium/Skov/Update.hs [hunk 1]
```diff
@@ -221,6 +241,10 @@ processFinalization newFinBlock finRec@FinalizationRecord{..} = do
                     _ -> return prunedbrs
         newBranches <- trimBranches unTrimmedBranches
         putBranches newBranches
+        -- mark dead blocks by increasing height
+        forM_ (toRemoveFromTrunk ++ reverse toRemoveFromBranches) $ \bp -> do
```
Comment (td202) [inline concordium-consensus/src/Concordium/Skov/Update.hs:245]: I think they should be removed by decreasing height to avoid having a live block with a dead parent.

File: concordium-consensus/src/Concordium/Skov/Update.hs [hunk 2]
```diff
@@ -162,18 +162,29 @@ processFinalization newFinBlock finRec@FinalizationRecord{..} = do
         -- We proceed backwards from the new finalized block, marking it and
         -- its ancestors as finalized, while other blocks at the same height
         -- are marked dead.
+        -- Instead of marking blocks dead immediately we accummulate them
```
Comment (td202) [inline concordium-consensus/src/Concordium/Skov/Update.hs:165]:
```suggestion
        -- Instead of marking blocks dead immediately we accumulate them
```

File: concordium-consensus/src/Concordium/Skov/Update.hs [hunk 3]
```diff
@@ -162,18 +162,29 @@ processFinalization newFinBlock finRec@FinalizationRecord{..} = do
...
+            pruneTrunk toRemove keeper (brs Seq.:|> l) = do
+                toRemove1 <- foldM (\remove bp -> if bp == keeper then do
+                                      markFinalized (getHash bp) finRec
+                                      logEvent Skov LLDebug $ "Block " ++ show bp ++ " marked finalized"
+                                      return remove
+                                    else
+                                      return (bp:remove)
+                                  )
+                            toRemove
+                            l
```
Comment (td202) [inline concordium-consensus/src/Concordium/Skov/Update.hs:185]:
```suggestion
                markFinalized (getHash keeper) finRec
                logEvent Skov LLDebug $ "Block " ++ show keeper ++ " marked finalized"
                let toRemove1 = filter (/= keeper) l ++ toRemove
```

File: concordium-consensus/src/Concordium/Skov/Update.hs [hunk 4]
```diff
@@ -162,18 +162,29 @@ processFinalization newFinBlock finRec@FinalizationRecord{..} = do
...
                 parent <- bpParent keeper
-                pruneTrunk parent brs
+                toRemove2 <- pruneTrunk toRemove1 parent brs
```
Comment (td202) [inline concordium-consensus/src/Concordium/Skov/Update.hs:187]: It might be preferable to call `markFinalized` after the recursive call to ensure that blocks are marked finalized in increasing height order. (This would also be useful for database recovery, since it would be convenient to assume that if a block is in the database then its parent will also be there.)

**Review by td202 — CHANGES_REQUESTED** [review]

File: concordium-consensus/src/Concordium/Skov/Update.hs (hunk 1 above)
Comment (abizjak) [reply concordium-consensus/src/Concordium/Skov/Update.hs:245]: I think at this point it should not matter, but I don't have any objections to it either.

File: concordium-consensus/src/Concordium/Skov/Update.hs (hunk 3 above)
Comment (abizjak) [reply concordium-consensus/src/Concordium/Skov/Update.hs]: Added.

File: concordium-consensus/src/Concordium/Skov/Update.hs (hunk 2 above)
Comment (abizjak) [reply concordium-consensus/src/Concordium/Skov/Update.hs]: Changed.

File: concordium-consensus/src/Concordium/Skov/Update.hs [hunk 5]
```diff
@@ -196,21 +203,29 @@ processFinalization newFinBlock finRec@FinalizationRecord{..} = do
         doArchive =<< bpParent newFinBlock
         -- Prune the branches: mark dead any block that doesn't descend from
         -- the newly-finalized block.
+        -- Instead of marking blocks dead immediately we accummulate them
```
Comment (td202) [inline concordium-consensus/src/Concordium/Skov/Update.hs:206]:
```suggestion
        -- Instead of marking blocks dead immediately we accumulate them
```

**Review by td202 — APPROVED** [review]
One typo, otherwise looks fine. If this will be a release, be sure to update `service/windows/installer/Node.wxs`.

File: concordium-consensus/src/Concordium/Skov/Update.hs (hunk 5 above)
Comment (abizjak) [reply concordium-consensus/src/Concordium/Skov/Update.hs]: Resolved.
