### PR TITLE
Database and catch-up fixes

### LINKED ISSUE #958: Catch up loops or soft-bans peer
**Bug Description**

In-band catch-up can be observed to fail in the following ways:
- After receiving the catch-up response, the node soft-bans the peer, citing "Catching up with peer {} resulted in incompatible globalstates, dropping and soft-banning".
- After receiving the catch-up response, the node repeatedly attempts to catch-up with the peer. This ends when a new block is produced and distributed.

In both cases, this is caused by the node failing to properly process the catch-up response. In particular, the highest quorum certificate is not processed where the QC is also part of the finalization entry. If there is also a timeout certificate or quorum/timeout messages, these will cause the response to be rejected resulting in a ban. (This is since failing to process the QC results in a state where they cannot be processed.) Otherwise, the node will detect that it has still not caught up successfully and retry, resulting in the looping behaviour. When a block is eventually produced, this (should) lead to the highest QC actually getting updated, ending the loop.

**Steps to Reproduce**

Run a chain with multiple nodes. (Minimum block time should be at least 1 second to give a chance of observing the behaviour.) Have a node catch-up. To observe the soft-ban behaviour, it is easiest to have some bakers offline, so that timeouts occur - especially if the catching-up node is required to make the 2/3 committee online.

**Expected Result**

The node should not loop in catch-up or ban its (well-behaved) peers.

**Actual Result**

The node may loop in catch-up or ban peers.

**Versions**
- Software Version: 6.0.0, 6.0.1
- OS: All

### PR DESCRIPTION
**Pull request by td202**
## Purpose

This addresses:

#947: Database truncation fails during roll-back on Windows
#958: Catch-up loops or soft-bans peers

## Changes

- When attempting to read beyond the end of the block state database, the file is remapped. This is changed so that the file is not remapped unless it is longer than the existing map. This addresses #947 because the file cannot be truncated on Windows while it is memory-mapped. The roll-back process can attempt to read beyond the end of the database multiple times, causing the file to be mapped repeatedly (prior to this change). When truncating the file, only the latest mapping is forced to close, and thus the other mappings can cause failure.
- Process the quorum certificate for the highest certified block before the finalization entry. Also, change the criterion for doing so to be that it will advance the round (rather than we have already checked such a QC). This resolves #958.
- Fix an issue with accounting for which blocks are rolled back. This mainly affects logging, but could cause some misbehaviour if only one block is rolled back.
- Additional trace-level logging of catch-up messages.

## Checklist

- [x] My code follows the style of this project.
- [x] The code compiles without warnings.
- [x] I have performed a self-review of the changes.
- [x] I have documented my code, in particular the intent of the
      hard-to-understand areas.
- [x] (If necessary) I have updated the CHANGELOG.

### CODE REVIEW

File: concordium-consensus/src/Concordium/KonsensusV1/TreeState/LowLevel/LMDB.hs [hunk 1]
```diff
@@ -851,7 +851,20 @@ rollBackBlocksUntil checkState = do
             throwM . DatabaseRecoveryFailure $
                 "Genesis block state could not be recovered."
         (count', hashes, newLastFin) <- asWriteTransaction $ \dbh txn -> do
-            let loop !c hashes fin finQC = case stbBlock fin of
+            let loop ::
+                    -- Current count of blocks rolled back
+                    Int ->
+                    -- Accumulated list of rolled-back finalized blocks
```
Comment (abizjak) [inline concordium-consensus/src/Concordium/KonsensusV1/TreeState/LowLevel/LMDB.hs:857]: Can you elaborate on the order of this list please.

File: concordium-consensus/src/Concordium/KonsensusV1/TreeState/LowLevel/LMDB.hs [hunk 2]
```diff
@@ -851,7 +851,20 @@ rollBackBlocksUntil checkState = do
...
+                    [BlockHash] ->
+                    -- Block to roll back
+                    StoredBlock pv ->
+                    -- Quorum certificate on the block
+                    QuorumCertificate ->
+                    -- Total number of blocks rolled back,
+                    -- List of hashes of rolled-back blocks,
```
Comment (abizjak) [inline concordium-consensus/src/Concordium/KonsensusV1/TreeState/LowLevel/LMDB.hs:864]: And here.

File: concordium-consensus/src/Concordium/KonsensusV1/Consensus/CatchUp.hs [hunk 3]
```diff
@@ -435,8 +435,8 @@ processCatchUpTerminalData ::
     CatchUpTerminalData ->
     m TerminalDataResult
 processCatchUpTerminalData CatchUpTerminalData{..} = flip runContT return $ do
-    progress0 <- processFE False cutdLatestFinalizationEntry
-    progress1 <- foldM processQC progress0 cutdHighestQuorumCertificate
+    progress0 <- foldM processQC False cutdHighestQuorumCertificate
+    progress1 <- processFE progress0 cutdLatestFinalizationEntry
```
Comment (abizjak) [inline concordium-consensus/src/Concordium/KonsensusV1/Consensus/CatchUp.hs:439]: Seeing that there seemed to have been a bug here, can you please add documentation as to why this order is correct, and not the previous one?

**Review by abizjak — APPROVED** [review]

File: concordium-consensus/src/Concordium/KonsensusV1/Consensus/CatchUp.hs (hunk 3 above)
Comment (td202) [reply concordium-consensus/src/Concordium/KonsensusV1/Consensus/CatchUp.hs]: The old ordering isn't wrong per se, but this is more efficient. The bug was caused by relying on `roundExistingQCs` to determine if the QC was worth processing. While the finalization entry was generally the trigger for the bug (because it was processed first), the bug could still potentially be triggered even with the reordering.

Comment (abizjak) [reply concordium-consensus/src/Concordium/KonsensusV1/Consensus/CatchUp.hs]: Thanks. But if this is more efficient than that is still useful insight that should be documented.
